// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';

// Validate environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const errorMsg = 'Missing Supabase environment variables. Please set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your Vercel project settings.';
  console.error(errorMsg);
  
  // Only show console warnings in development
  if (typeof window !== 'undefined' && import.meta.env.DEV) {
    console.warn('⚠️ Supabase configuration missing. Authentication will not work until environment variables are set.');
    console.warn('📝 To fix: Go to Vercel Dashboard → Your Project → Settings → Environment Variables');
    console.warn('   Add: VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY');
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create client with fallback values to prevent crashes
// The client will still be created even without credentials, but auth operations will fail gracefully
let supabase: ReturnType<typeof createClient<Database>>;

try {
  supabase = createClient<Database>(
    SUPABASE_URL || 'https://placeholder.supabase.co', 
    SUPABASE_PUBLISHABLE_KEY || 'placeholder-key', 
    {
  auth: {
        storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
        detectSessionInUrl: true,
      }
    }
  );
} catch (error) {
  console.error('Failed to create Supabase client:', error);
  // Create a minimal client to prevent app crash
  supabase = createClient<Database>(
    'https://placeholder.supabase.co',
    'placeholder-key',
    {
      auth: {
        storage: typeof window !== 'undefined' ? localStorage : undefined,
        persistSession: false,
        autoRefreshToken: false,
  }
    }
  );
}

export { supabase };